---
name: phpcs
on: [pull_request]

jobs:

  phpcs:
    name: "7.4"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up environment
        uses: shivammathur/setup-php@master
        with:
          php-version: "7.4"
          extensions: mbstring, dom, fileinfo

      - name: Install dependencies
        run: composer install --no-suggest --prefer-dist --optimize-autoloader

      - name: Check code style
        run: ./vendor/bin/phpcs
