---
name: phpunit
on: [pull_request]

jobs:

  phpunit:
    name: ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["7.2", "7.3", "7.4"]
    steps:
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up environment
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit for testing and coverage
        uses: theomessin/action-phpcov@master
        with:
          min_coverage: 85
          now_project: "laravel-stalker-phpcov"
          now_token: ${{ secrets.NOW_TOKEN }}
          phpunit: "./vendor/bin/phpunit --testdox"
